version: '3'

volumes:
    home:
    ldap_data:
    slapd_data:

services:
  ldapservice:
    build:
        context: ldapserver
        dockerfile: Dockerfile
    image: ldapimmage
    hostname: ldapserver.cyolauth.org
    container_name: ldapserver
    ## The following environment variables
    ## are required. We suggest you create
    ## an ldap-vars.env and configure them.
    #environment:
    #    - LDAP_ORGANISATION=rahasak
    #    - LDAP_DOMAIN=rahasak.com
    #    - "LDAP_BASE_DN=dc=rahasak,dc=com"
    #    - LDAP_ADMIN_PASSWORD=rahasak
    env_file:
        - ldap-vars.env
    volumes:
        - ldap_data:/var/lib/ldap
        - slapd_data:/etc/ldap/slapd.d

  cyolauthservice:
    build:
        context: .
        dockerfile: Dockerfile
    image: stevenrbrandt/cyolauth
    container_name: cyolauth
    hostname: cyolauthhost.cyolauth.org
    volumes:
        - /home/sbrandt/repos/cyolauthenticator:/usr/local/lib/python3.8/dist-packages/cyolauthenticator
    env_file:
        - ldap-vars.env
    ports:
      - 9443:443
      - 9080:80
    volumes:
      - home:/home
