version: '3'

services:
  ldapservice:
    build:
        context: ldapserver
        dockerfile: Dockerfile
    image: stevenrbrandt/ldapimmage
    hostname: ldapserver.cyolauth.org
    container_name: ldapserver
    ## The following environment variables
    ## are required. We suggest you create
    ## an ldap-vars.env and configure them.
    #environment:
    #    - LDAP_ORGANISATION=rahasak
    #    - LDAP_DOMAIN=rahasak.com
    #    - "LDAP_BASE_DN=dc=rahasak,dc=com"
    #    - LDAP_ADMIN_PASSWORD=rahasak
    env_file:
        - ldap-vars.env
    volumes:
        - /home/sbrandt/tmp/ldap_data:/var/lib/ldap
        - /home/sbrandt/tmp/slapd_data:/etc/ldap/slapd.d

  cyolauthservice:
    build:
        context: .
        dockerfile: Dockerfile
    image: stevenrbrandt/cyolauth
    container_name: cyolauth
    hostname: cyolauthhost.cyolauth.org
    env_file:
        - ldap-vars.env
    ports:
      - 9443:443
      - 9080:80
    entrypoint: sleep infinity
    volumes:
      - /home/sbrandt/repos/cyolauthenticator:/root/cyolauthenticator
      - /home/brandt/tmp/home:/home
      - ./tls:/etc/pki/tls
