version: '3'

services:

  cyolauth:
    build:
        context: .
        dockerfile: Dockerfile
    image: cyolauth
    container_name: cyolauth
    hostname: cyolauthhost
    ports:
      - 9443:443
      - 9080:80
